In [3]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (2.34.2)
Requirement already satisfied: beautifulsoup4 in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (4.15.0)
Requirement already satisfied: pandas in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (3.0.5)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\bhoom\anaconda3\envs\myenv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

base_url = "https://books.toscrape.com/catalogue/page-{}.html"

books = []

for page in range(1, 51):

    url = base_url.format(page)
    response = requests.get(url)

    if response.status_code == 200:

        soup = BeautifulSoup(response.text, "html.parser")

        for book in soup.select("article.product_pod"):

            # Basic information
            title = book.h3.a["title"]
            price = book.select_one(".price_color").text.strip()
            availability = book.select_one(".availability").text.strip()
            rating = book.select_one(".star-rating")["class"][1]

            # Book detail page URL
            book_url = "https://books.toscrape.com/catalogue/" + book.h3.a["href"]

            # Open individual book page
            book_response = requests.get(book_url)
            book_soup = BeautifulSoup(book_response.text, "html.parser")

            # Category
            category = book_soup.select("ul.breadcrumb li a")[-1].text.strip()

            # Number of reviews
            table = book_soup.select_one("table.table-striped")
            rows = table.select("tr")

            num_reviews = None

            for row in rows:
                cells = row.select("td")

                if len(cells) == 2 and cells[0].text.strip() == "Number of reviews":
                    num_reviews = cells[1].text.strip()

            books.append({
                "Name": title,
                "Price": price,
                "Rating": rating,
                "Availability": availability,
                "Category": category,
                "Number of Reviews": num_reviews,
                "URL": book_url
            })

        print(f"Page {page} scraped successfully")

    else:
        print(f"Error on page {page}: {response.status_code}")

    time.sleep(0.5)


df = pd.DataFrame(books)

print(df.head())
print(df.shape)

Page 1 scraped successfully
Page 2 scraped successfully
Page 3 scraped successfully
Page 4 scraped successfully
Page 5 scraped successfully
Page 6 scraped successfully

KeyboardInterrupt:

In [5]:
df

,Name,Price,Rating,Availability,Category,Number of Reviews,URL
0,A Light in the Attic,Â£51.77,Three,In stock,Poetry,None,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,Â£53.74,One,In stock,Historical Fiction,None,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,Â£50.10,One,In stock,Fiction,None,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,Â£47.82,Four,In stock,Mystery,None,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,History,None,https://books.toscrape.com/catalogue/sapiens-a...
...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,Â£55.53,One,In stock,Classics,None,https://books.toscrape.com/catalogue/alice-in-...
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â£57.06,Four,In stock,Sequential Art,None,https://books.toscrape.com/catalogue/ajin-demi...
997,A Spy's Devotion (The Regency Spies of London #1),Â£16.97,Five,In stock,Historical Fiction,None,https://books.toscrape.com/catalogue/a-spys-de...
998,1st to Die (Women's Murder Club #1),Â£53.98,One,In stock,Mystery,None,https://books.toscrape.com/catalogue/1st-to-di...
999,"1,000 Places to See Before You Die",Â£26.08,Five,In stock,Travel,None,https://books.toscrape.com/catalogue/1000-plac...

In [6]:
df.to_csv("books_data.csv", index=False)

In [5]:
df = pd.read_csv("C:\\Users\\bhoom\\OneDrive\\Desktop\\book_scraping\\books_data.csv")

In [6]:
df.columns

Index(['Name', 'Price', 'Rating', 'Availability', 'Category',
       'Number of Reviews', 'URL'],
      dtype='str')

In [8]:
# Name

df["Name"].isna().sum()

np.int64(0)

In [9]:
df["Name"].duplicated().sum()

np.int64(1)

In [9]:
# Price

df["Price"].isna().sum()

np.int64(0)

In [11]:
df["Price"].dtypes

In [12]:
df["Price"].unique()

<StringArray>
['Â£51.77', 'Â£53.74', 'Â£50.10', 'Â£47.82', 'Â£54.23', 'Â£22.65', 'Â£33.34',
 'Â£17.93', 'Â£22.60', 'Â£52.15',
 ...
 'Â£41.24', 'Â£39.07', 'Â£29.82', 'Â£37.26', 'Â£20.30', 'Â£34.65', 'Â£43.38',
 'Â£57.06', 'Â£16.97', 'Â£26.08']
Length: 903, dtype: str

In [13]:
df["Price"] = (
    df["Price"]
    .str.replace("Â£", "", regex=False)
    .str.strip()
    .astype(float)
)

In [14]:
df["Price"].unique()

array([51.77, 53.74, 50.1 , 47.82, 54.23, 22.65, 33.34, 17.93, 22.6 ,
       52.15, 13.99, 20.66, 17.46, 52.29, 35.02, 57.25, 23.88, 37.59,
       51.33, 45.17, 12.84, 37.32, 30.52, 25.27, 34.53, 54.64, 22.5 ,
       53.13, 40.3 , 44.18, 17.66, 31.05, 23.82, 36.89, 15.94, 33.29,
       18.02, 19.63, 52.22, 33.63, 57.31, 26.41, 47.61, 23.11, 45.07,
       31.77, 50.27, 14.27, 18.78, 25.52, 16.28, 31.12, 19.49, 17.27,
       19.09, 56.13, 56.41, 56.5 , 45.22, 38.16, 54.11, 42.96, 23.89,
       16.77, 20.59, 37.13, 56.06, 58.11, 49.05, 40.76, 19.73, 32.24,
       41.83, 39.58, 39.25, 25.02, 51.04, 19.83, 50.4 , 13.61, 13.34,
       18.97, 36.28, 10.16, 15.44, 48.41, 46.35, 14.07, 14.86, 33.37,
       56.4 , 14.02, 46.91, 45.61, 19.92, 40.11, 53.9 , 35.67, 22.  ,
       57.36, 29.17, 54.63, 46.03, 33.97, 22.11, 29.69, 15.97, 21.96,
       54.35, 37.97, 51.99, 43.29, 36.72, 17.08, 29.14, 28.81, 49.46,
       37.92, 28.09, 30.81, 42.95, 56.76, 16.64, 55.53, 28.13, 52.37,
       54.  , 21.87, 43.3 , 21.04, 41.6 , 35.07, 59.64, 52.72, 58.08,
       24.12, 42.15, 12.61, 17.44, 33.14, 27.37, 51.36, 36.  , 10.65,
       43.54, 38.21, 37.34, 44.1 , 55.85, 37.6 , 10.97, 41.82, 36.95,
       44.28, 55.02, 17.24, 23.15, 41.25, 32.  , 38.49, 10.93, 27.55,
       55.99, 16.24, 26.12, 12.23, 23.99, 29.06, 20.27, 43.55, 36.94,
       20.47, 41.06, 14.19, 38.28, 41.05, 30.25, 28.26, 10.76, 16.85,
       13.47, 48.56, 19.15, 42.98, 22.16, 49.43, 29.99, 21.36, 29.  ,
       53.53, 41.62, 54.59, 34.95, 37.72, 35.61, 42.16, 19.19, 19.43,
       37.8 , 30.8 , 27.43, 11.11, 36.5 , 15.38, 15.48, 46.82, 18.46,
       36.58, 50.54, 12.51, 24.7 , 43.61, 14.36, 52.65, 38.2 , 19.6 ,
       12.96, 37.1 , 46.31, 45.95, 22.08, 25.38, 27.12, 43.04, 56.8 ,
       25.91, 32.61, 27.88, 52.67, 46.02, 44.48, 37.4 , 54.04, 16.88,
       28.08, 10.4 , 44.07, 23.4 , 17.43, 54.21, 40.67, 52.26, 28.77,
       13.82, 25.85, 48.78, 35.35, 44.73, 15.77, 39.24, 13.92, 10.69,
       45.21, 45.58, 11.89, 39.5 , 44.74, 52.79, 35.43, 55.84, 48.87,
       46.78, 25.48, 23.57, 50.89, 10.56, 18.28, 11.83, 21.95, 38.39,
       41.56, 24.48, 40.36, 28.9 , 37.61, 38.85, 53.95, 49.83, 51.51,
       18.03, 26.79, 19.55, 29.65, 25.98, 10.6 , 14.75, 47.02, 28.82,
       58.79, 10.23, 30.03, 45.84, 15.06, 46.47, 27.09, 57.62, 14.39,
       51.75, 54.07, 55.35, 40.12, 37.51, 11.21, 47.72, 25.01, 22.13,
       44.14, 56.02, 11.23, 43.28, 47.27, 20.29, 50.83, 31.85, 46.23,
       49.32, 32.01, 28.01, 50.62, 17.03, 48.8 , 58.14, 34.2 , 51.48,
       29.87, 10.9 , 56.37, 48.35, 16.73, 56.48, 40.79, 39.72, 14.58,
       55.51, 21.8 , 13.33, 38.73, 37.86, 11.53, 27.06, 13.86, 37.55,
       32.3 , 46.29, 26.2 , 33.26, 59.15, 39.43, 14.44, 56.54, 59.9 ,
       11.88, 48.05, 21.21, 49.67, 43.14, 36.97, 26.8 , 15.71, 54.65,
       54.36, 35.28, 20.55, 58.32, 11.84, 41.46, 20.1 , 56.86, 56.51,
       40.83, 48.64, 59.48, 39.01, 38.77, 48.39, 27.26, 11.68, 59.45,
       21.  , 53.98, 48.74, 21.15, 13.71, 47.67, 16.89, 27.18, 17.28,
       45.14, 40.85, 20.46, 56.27, 48.49, 51.34, 16.34, 20.5 , 21.59,
       20.88, 19.53, 48.48, 24.57, 49.71, 48.27, 58.05, 58.87, 11.82,
       28.03, 44.05, 12.34, 16.68, 55.91, 52.98, 54.4 , 54.81, 25.08,
       10.41, 47.44, 20.91, 33.95, 43.68, 33.23, 35.92, 48.63, 56.63,
       50.49, 35.79, 34.06, 17.76, 39.36, 43.62, 43.02, 28.45, 41.39,
       51.15, 35.88, 36.91, 28.93, 38.89, 58.33, 39.67, 14.1 , 21.82,
       31.19, 53.64, 36.39, 58.54, 29.48, 25.06, 12.55, 29.04, 40.72,
       45.05, 47.13, 20.22, 44.21, 40.45, 10.29, 52.86, 55.65, 43.64,
       28.41, 11.45, 19.22, 56.91, 55.06, 13.2 , 53.63, 12.08, 22.14,
       25.37, 46.33, 37.33, 25.55, 34.72, 35.96, 41.14, 10.01, 36.05,
       49.03, 39.55, 16.62, 42.78, 52.3 , 32.34, 33.17, 20.12, 20.9 ,
       40.2 , 52.87, 51.74, 34.41, 32.38, 50.35, 11.38, 43.58, 13.22,
       51.17, 39.61, 57.43, 46.01, 28.25, 37.05, 19.57, 45.13, 46.64,
       12.16, 20.89, 17.97, 52.6 , 25.77, 48.19, 29.93, 44.34, 52.4 ,
       44.81, 57.84, 24.8 , 31.58, 43.27, 17.8 , 30.54, 18.77, 46.85,
       15.79, 10.27, 15.42, 59.92, 50.96, 30.6 , 19.27, 46.58, 48.51,
       19.02, 38.38, 49.98, 46.49, 18.32, 42.14, 56.59, 20.96, 40.32,
       58.55, 21.3 , 56.88, 32.97, 47.31, 48.67, 41.73, 53.68, 14.64,
       38.4 , 15.08, 30.57, 57.74, 11.05, 28.58, 42.91, 24.73, 13.76,
       45.56, 47.22, 56.  , 44.58, 34.5 , 11.33, 45.51, 41.81, 25.15,
       34.22, 16.23, 11.48, 23.37, 31.63, 24.91, 22.54, 23.63, 13.12,
       59.98, 31.49, 15.52, 48.13, 38.13, 36.55, 23.32, 16.33, 32.42,
       16.96, 22.37, 42.27, 38.7 , 35.63, 58.  , 52.41, 32.35, 20.75,
       17.49, 34.13, 58.81, 10.  , 51.22, 58.59, 31.3 , 46.42, 17.21,
       10.79, 52.35, 50.26, 59.99, 28.32, 38.71, 29.85, 14.82, 16.81,
       28.23, 52.11, 59.71, 46.08, 13.73, 49.45, 19.67, 12.36, 20.02,
       12.75, 47.51, 20.44, 34.79, 28.07, 13.9 , 24.17, 48.75, 14.74,
       32.49, 27.8 , 26.77, 50.44, 34.93, 12.87, 48.94, 13.38, 58.63,
       21.94, 26.58, 57.22, 56.43, 27.62, 49.56, 34.77, 17.73, 18.13,
       30.89, 31.95, 24.04, 32.36, 21.07, 50.66, 13.66, 58.09, 30.  ,
       32.74, 41.93, 42.8 , 53.51, 23.21, 21.14, 56.07, 14.41, 45.75,
       10.02, 48.77, 57.86, 23.59, 23.05, 55.55, 58.64, 42.57, 10.92,
       35.66, 37.19, 12.25, 29.7 , 36.8 , 45.43, 26.26, 44.92, 52.53,
       37.25, 20.93, 43.59, 33.92, 29.64, 27.41, 52.51, 47.8 , 14.54,
       49.53, 12.3 , 49.47, 57.48, 43.45, 13.03, 57.35, 44.29, 52.25,
       26.33, 22.96, 19.21, 26.78, 41.32, 24.55, 16.26, 47.84, 53.49,
       44.84, 53.71, 23.43, 34.32, 22.1 , 25.83, 36.74, 49.51, 48.96,
       54.62, 24.72, 46.45, 52.33, 14.57, 21.57, 12.91, 50.11, 41.67,
       44.88, 11.1 , 28.54, 19.07, 43.63, 39.13, 56.68, 14.16, 31.45,
       24.61, 32.87, 40.17, 13.51, 38.95, 31.69, 29.4 , 57.83, 55.46,
       57.6 , 34.98, 11.87, 12.47, 59.04, 26.13, 22.2 , 45.11, 43.69,
       55.5 , 53.04, 44.97, 42.38, 20.11, 56.7 , 41.  , 28.85, 49.97,
       19.69, 28.88, 43.7 , 54.89, 37.52, 51.07, 42.72, 26.66, 42.21,
       46.83, 21.28, 15.36, 38.62, 25.4 , 43.87, 18.74, 54.86, 52.62,
       15.28, 17.81, 23.9 , 49.13, 10.62, 36.17, 59.95, 26.09, 37.35,
       51.32, 21.12, 27.35, 21.74, 40.87, 49.31, 20.79, 38.35, 21.55,
       38.02, 22.06, 10.66, 56.58, 36.83, 35.01, 30.48, 14.08, 31.22,
       54.29, 31.04, 31.38, 16.78, 24.42, 11.75, 12.86, 34.  , 57.42,
       53.47, 11.64, 52.88, 18.51, 39.77, 51.96, 39.51, 15.4 , 53.82,
       30.95, 57.82, 48.71, 36.52, 43.19, 36.25, 29.45, 34.56, 54.12,
       33.78, 57.7 , 36.34, 50.59, 29.38, 45.42, 54.43, 36.26, 16.16,
       36.29, 27.89, 12.29, 15.85, 14.4 , 19.18, 10.64, 14.76, 57.49,
       30.66, 18.88, 42.12, 42.4 , 58.35, 21.72, 44.91, 37.46, 28.48,
       28.34, 46.96, 24.96, 21.71, 28.99, 52.94, 55.66, 39.45, 47.11,
       58.75, 38.92, 39.39, 25.89, 27.7 , 24.89, 58.99, 57.2 , 38.43,
       34.74, 40.44, 45.24, 34.96, 40.28, 38.  , 28.8 , 32.93, 47.09,
       28.42, 22.85, 41.24, 39.07, 29.82, 37.26, 20.3 , 34.65, 43.38,
       57.06, 16.97, 26.08])

In [ ]:
df.rename(columns={"Price": "Price in £"}, inplace=True)

In [16]:
df

,Name,Price in £,Rating,Availability,Category,Number of Reviews,URL
0,A Light in the Attic,51.77,Three,In stock,Poetry,NaN,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,53.74,One,In stock,Historical Fiction,NaN,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,50.10,One,In stock,Fiction,NaN,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,47.82,Four,In stock,Mystery,NaN,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,54.23,Five,In stock,History,NaN,https://books.toscrape.com/catalogue/sapiens-a...
...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,55.53,One,In stock,Classics,NaN,https://books.toscrape.com/catalogue/alice-in-...
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",57.06,Four,In stock,Sequential Art,NaN,https://books.toscrape.com/catalogue/ajin-demi...
997,A Spy's Devotion (The Regency Spies of London #1),16.97,Five,In stock,Historical Fiction,NaN,https://books.toscrape.com/catalogue/a-spys-de...
998,1st to Die (Women's Murder Club #1),53.98,One,In stock,Mystery,NaN,https://books.toscrape.com/catalogue/1st-to-di...
999,"1,000 Places to See Before You Die",26.08,Five,In stock,Travel,NaN,https://books.toscrape.com/catalogue/1000-plac...

In [17]:
df["Price in £"].isna().sum()

np.int64(0)

In [18]:
df["Price in £"].duplicated().sum()

np.int64(97)

In [19]:
df["Price in £"].dtypes

dtype('float64')

In [20]:
# Rating

df["Rating"].isna().sum()

np.int64(0)

In [22]:
df["Rating"].duplicated().sum()

np.int64(995)

In [23]:
df["Rating"].unique()

<StringArray>
['Three', 'One', 'Four', 'Five', 'Two']
Length: 5, dtype: str

In [27]:
df["Rating"] = df["Rating"].replace({
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
})
df["Rating"] = pd.to_numeric(df["Rating"])

In [28]:
df["Rating"].unique()

array([3, 1, 4, 5, 2])

In [29]:
df["Rating"].dtypes

dtype('int64')

In [30]:
# Availability

df["Availability"].isna().sum()

np.int64(0)

In [31]:
df["Availability"].duplicated().sum()

np.int64(999)

In [32]:
df["Availability"].unique()

<StringArray>
['In stock']
Length: 1, dtype: str

In [33]:
# Category

df["Category"].isna().sum()

np.int64(0)

In [34]:
df["Category"].duplicated().sum()

np.int64(950)

In [35]:
df["Category"].unique()

<StringArray>
[            'Poetry', 'Historical Fiction',            'Fiction',
            'Mystery',            'History',        'Young Adult',
           'Business',            'Default',     'Sequential Art',
              'Music',    'Science Fiction',           'Politics',
             'Travel',           'Thriller',     'Food and Drink',
            'Romance',          'Childrens',         'Nonfiction',
                'Art',       'Spirituality',         'Philosophy',
          'New Adult',       'Contemporary',            'Fantasy',
      'Add a comment',            'Science',             'Health',
             'Horror',          'Self Help',           'Religion',
          'Christian',              'Crime',      'Autobiography',
  'Christian Fiction',          'Biography',     'Womens Fiction',
            'Erotica',           'Cultural',         'Psychology',
              'Humor',         'Historical',             'Novels',
      'Short Stories',           'Suspense',           'Classics',
           'Academic',   'Sports and Games',      'Adult Fiction',
          'Parenting',         'Paranormal']
Length: 50, dtype: str

In [37]:
# Number of Reviews	

df["Number of Reviews"].isna().sum()

np.int64(1000)

In [38]:
df["Number of Reviews"]=df["Number of Reviews"].fillna(0)

In [39]:
df["Number of Reviews"].isna().sum()

np.int64(0)

In [ ]:
# URL

df["URL"].isna().sum()

np.int64(0)

In [41]:
df["URL"].duplicated().sum()

np.int64(0)

In [42]:
df["URL"].dtypes

In [43]:
df

,Name,Price in £,Rating,Availability,Category,Number of Reviews,URL
0,A Light in the Attic,51.77,3,In stock,Poetry,0.0,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,53.74,1,In stock,Historical Fiction,0.0,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,50.10,1,In stock,Fiction,0.0,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,47.82,4,In stock,Mystery,0.0,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,History,0.0,https://books.toscrape.com/catalogue/sapiens-a...
...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,55.53,1,In stock,Classics,0.0,https://books.toscrape.com/catalogue/alice-in-...
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",57.06,4,In stock,Sequential Art,0.0,https://books.toscrape.com/catalogue/ajin-demi...
997,A Spy's Devotion (The Regency Spies of London #1),16.97,5,In stock,Historical Fiction,0.0,https://books.toscrape.com/catalogue/a-spys-de...
998,1st to Die (Women's Murder Club #1),53.98,1,In stock,Mystery,0.0,https://books.toscrape.com/catalogue/1st-to-di...
999,"1,000 Places to See Before You Die",26.08,5,In stock,Travel,0.0,https://books.toscrape.com/catalogue/1000-plac...

In [44]:
df.to_csv("Books_online_cleaned_dataset.csv", index=False)